[build]
  command = "npx prisma db push --schema=apps/web/prisma/schema.prisma && pnpm --filter @tobie/web db:seed && pnpm --filter @tobie/web... build"
  publish = "apps/web/.next"

[dev]
  command = "pnpm dev"

[[plugins]]
  package = "@netlify/plugin-nextjs"
